Add string dump and conversion functions for 64bit types
DanielJerolm/gpcc pull request #8
Opened 2024-12-05 21:26 UTC by DanielJerolm

`gpcc::string` is missing string conversion functions for 64bit integral values. This PR adds the following functions:
- A set of `*ToU64()` functions for conversion of strings in different formats to `uint64_t`
- A set of `*ToI64()` functions for conversion of strings in different formats to `int64_t`
- `ToHex()`, `ToBin()`, `ToHexNoPrefix()`, `ToDecAndHex()` are template functions now to support multiple integral types incl. 64 bit types.

`gpcc::string::HexDump()` has been enhanced:
- The address parameter is `uintptr_t` now instead of `uint32_t` to enable use on 64bit systems
- Some parameters are by-reference now. This allows `HexDump()` to update them and simplify usage of `HexDump()` if multiple lines shall be generated.

The signature of `gpcc::string::HexDump()` has been changed. **This is a breaking change.**

2024-12-20 19:49 UTC, Andreas143 reviewed
The changes to HexDump() are not so lucky. See details within file comments.

2024-12-20 19:49 UTC, Andreas143 commented on src/string/tools.cpp
> +                    uint_fast8_t wordsPerLine)
This function has some suprising facts.
1.) There are more IN/OUT parameters that someone would expect, The original declaration was simpler in this case. Ok, the changes has been introduce for convenience reason (as noted), but it lacks some intuitiveness now.
2.) The docu tells, that the function "Creates a string ...", BUT it misses the point that exactly one line is contained. The text "chunk of binary data" is not specific enough to be clear. The number of 'wordsPerLine is created exactly! The name of the function doesn't tell that either. Furthermore it suggests that multiple lines of hex dump are contained in the output string. On the other hand there is a small tip in the docu (the loop example) but that doesn't make up for it.
Finally, I think this function should be a little bit redesigned. It should not need IN/OUT parameters. It should clearly point out that exactly one line is contained in the output string. For loop usage this should not be so much unconvenient.

2024-12-22 11:55 UTC, DanielJerolm commented on src/string/tools.cpp
> +                    uint_fast8_t wordsPerLine)
What do you thing about introducing a class `BinaryDumper` or something. It's constructor could take all the settings and parameters plus the pointer to the binary data. Then the user could pop the dump line by line from the instance. The user could also fetch a suitable headline from the instance:
```
BinaryDumper bd(address, pData, n, wordSize, wordsPerLine);
cli.WriteLine(bd.GetHeadLine());
std::string s = bd.GetLine();
while (!s.empty())
{
  cli.WriteLine(std::move(s));
  s = bd.GetLine();
}
```

2024-12-27 11:13 UTC, Andreas143 commented on src/string/tools.cpp
> +                    uint_fast8_t wordsPerLine)
Yes, I think this is a great idea. I would suggest a small change to the c-tor's parameter list.
1.) The 'data' (input) related parameters (pData, n) should be located before the 'output' related parameters (address, wordSize, wordsPerLine)
2.) The parameter 'n' should be renamed to 'size', 'sizeOfData' or 'numOfBytes'.
3.) The parameter 'address' could be renamed to 'addrOfData' or 'startAddr'.
Example: BinaryDumper(pData, size, addrOfData, wordSize, wordsPerLine);

2025-01-10 13:36 UTC, DanielJerolm commented
After finishing review of class `BinaryDumper`, I would remove `gpcc::string::HexDump()` and switch the current two users of `HexDump()` to class `BinaryDumper`.

2025-01-17 14:59 UTC, Andreas143 requested changes

2025-01-17 14:59 UTC, Andreas143 commented on include/gpcc/string/BinaryDumper.hpp
> +                 uint8_t const wordSize);
The 'input' (binary data) related parameters (pData, nBytes) should be located before the 'output' (string) related parameters (address, wordSize).
```suggestion
    BinaryDumper(void const * const pData,
                 size_t const nBytes,
                 uintptr_t const address,
                 uint8_t const wordSize);
```

2025-01-17 14:59 UTC, Andreas143 commented on include/gpcc/string/BinaryDumper.hpp
> +                 uint8_t const wordSize);
This contructor (and the associated methods (IsMoreDataAccepted() and ProvideMoreData()) conflicts to documentation at L-61f.
The documented usage (Create>Use>Destroy) is straight foreward and simple (KISS). The possiblility to add 'data' later or to add other data (but please check preconditions) is not simple.
I would prefer to remove this 'feature'!

2025-01-17 14:59 UTC, Andreas143 commented on include/gpcc/string/BinaryDumper.hpp
> +    void ProvideMoreData(void const * const pData, size_t const nBytes);
The documented usage (Create>Use>Destroy) is straight foreward and simple (KISS). The possiblility to add 'data' later or to add other data (but please check preconditions) is not simple.
I would prefer to remove this 'feature'!

2025-01-17 14:59 UTC, Andreas143 commented on src/string/BinaryDumper.cpp
> + * - ...any subsequent call to @ref ProvideMoreData() will be rejected.
This seems to be inconsistent to the current features of this class.
BUT: The documented usage (Create>Use>Destroy) is straight foreward and simple (KISS). The possiblility to add 'data' later or to add other data (but please check preconditions) is not simple.
I would prefer to remove this 'feature'!

2025-01-17 21:44 UTC, DanielJerolm commented on include/gpcc/string/BinaryDumper.hpp
> +                 uint8_t const wordSize);
Yes makes sense, will be adopted.

2025-01-17 21:56 UTC, DanielJerolm commented on src/string/BinaryDumper.cpp
> + * - ...any subsequent call to @ref ProvideMoreData() will be rejected.
There are use cases where a large amount of data is dumped in a loop using a small buffer.
The user could create a new `BinaryDumper` instance for each chunk of data, but then he also needs to keep track of the address.
That could be simplified if the `BinaryDumper` had a method `GetAddress()` and copy/move assignment operators:
```
BinaryDumper bd(data1, nbytes1, address, wordsize);
// [...] (loop fetching lines from bd)
bd = BinaryDumper(data2, nbytes2, bd.GetAddress(), wordsize);
// [...] (loop fetching lines from bd)
// and so on...
```

2025-01-18 13:14 UTC, Andreas143 commented on src/string/BinaryDumper.cpp
> + * - ...any subsequent call to @ref ProvideMoreData() will be rejected.
I do not see the requirements for this approach. Indeed I do not understand the problem with 'large amount of data'.
The BinaryDumper needs a buffer for exactly one line no matter how large the whole memory block is. The user of BinaryDumper also doesn't need a big buffer per BinaryDumber instance. He creates an BD instance, calls GetHeadline() and then calls GetLine() in a loop as needed. There is no need for a big buffer. If a use case looks like the user stores multiple results of GetLine() into a smal buffer and then write this smal buffer to somewhere and then continue to invoke GetLine() then this is an issue of the user's app. This 'write small buffer with multiple lines of dumb' logic should then be part of the BinaryDumper usage loop. Or I'm missing something?
Example (pseudo code):
```bash
BinaryDumper bdOfBigData(pData, hugeNumberOfBytes, address, wordsize);
SmalBuffer buffer;
buffer := bdOfBigData.GetHeadLine();
while (not bdOfBigData.IsAllDataDumped()) {
  buffer := buffer + bdOfBigData.GetLine();
  if (buffer.full()) {
    writeToSomeWhere(buffer);
    buffer.clear();
  }
}
if ( not buffer.empty()) {
  writeToSomeWhere(buffer);
  buffer.clear();
}
```

2025-01-18 14:26 UTC, DanielJerolm commented on src/string/BinaryDumper.cpp
> + * - ...any subsequent call to @ref ProvideMoreData() will be rejected.
I don't mean the output buffer. The output buffer is small because the user can fetch the dump line-by-line.
The problem is the input buffer containing the binary data.
Consider dumping a file or some kind of record from a non-volatile storage on a resource-constraint embedded device. One could load it all into RAM (may consume several kB), or load it in small chunks (say 128 byte), dump it, and load the next chunk.

2025-01-18 18:17 UTC, Andreas143 commented on src/string/BinaryDumper.cpp
> + * - ...any subsequent call to @ref ProvideMoreData() will be rejected.
Ok, I think that I get it now. The user app has to copy the 'big' data from source memory into a smaller buffer and put that buffer into BinaryDumper because the BinaryDumper cannot access the source memory directly. Right?
But again this should be the issue of the user app and not the BinaryDumper. Furthermore this use case is simple to solve by the user app. The BinaryDumper still needs GetHeadLine(), GetLine() and IsAllDataDumped() only. There is no need to provide a GetAddress() or ProvideMoreData() method because the user app can manage the address information easily.
I will try another pseudo code example (note that some checks are missing here):
```bash
Pointer pBigData := <somewhere>;
Address address := <address of somewhere>;
Size nbOfBytes := <sizeofBigData>;
Buffer smalBuf;
Size smalBufSize := <fewBytes>; 
Flag getHeadline := true;
while (nbOfBytes != 0) {
  smalBuf := loadFromSourceMemory(pBigData, smalBufSize);
  BinaryDumper bd(&smalBuf, smalBufSize, address, wordSize);
  if (getHeadLine) {
    write(GetHeadLine());
    getHeadLine := false;
  }
  while ( not bd.IsAllDataDumped()) {
    write(bd.GetLine());
  }
  pBigData := pBigData + smalBufSize;
  nbOfBytes := nbOfBytes - smalBufSize;
  address := address + smalBufSize;
}
```

2025-01-19 09:53 UTC, DanielJerolm commented on src/string/BinaryDumper.cpp
> + * - ...any subsequent call to @ref ProvideMoreData() will be rejected.
Yes, that's what I meant. Your example shows the case. I see `ProvideMoreData()` would not provide too much simplification. I think it's not worth it and I'll remove it, but maybe provide a `GetAddress()` method.

2025-01-24 09:40 UTC, Andreas143 submitted a review, later dismissed

2025-01-26 17:54 UTC, Andreas143 approved these changes

2025-01-26 21:15 UTC, merged